set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Lint the Bun/TS source under apps/ponte/src
typecheck:
    biome lint ./apps/ponte/src

# Lint everything
all: typecheck