import {
  buildConfig,
  buildProjectConfig,
  type Config,
  type LockEntry,
  PROJECT_CONFIG_FILE,
  PROJECT_CONFIG_KEYS,
  type ProjectConfig,
  type ProjectLock,
  type Result,
  SKILL_TABLE_MIGRATION,
  type SourceEntry,
  SUBAGENT_TABLE_MIGRATION,
} from "@ponte/core";
import { z } from "zod";

export class ConfigError extends Error {
  readonly problems: readonly string[];
  constructor(problems: readonly string[]) {
    super(problems.join("\n"));
    this.problems = problems;
  }
}

const TYPE_WORDS: Record<string, string> = { object: "table", record: "table" };

const BARE_KEY = /^[A-Za-z0-9_-]+$/;

const LOCK_HEADER = "# generated by ponte - commit this file\n";

z.config({
  customError: issue =>
    issue.code !== "invalid_type"
      ? undefined
      : issue.input === undefined
        ? "is required"
        : `must be a ${TYPE_WORDS[issue.expected] ?? issue.expected}`,
});

const VENDOR_TABLE = z.record(
  z.string(),
  z.object({ enabled: z.boolean().optional() }),
);

const SOURCE_ENTRY = z.object({
  source: z.string(),
  ref: z.string().optional(),
  subdir: z.string().optional(),
});

const ENTRY_LIST = (table: string, migration: string) =>
  z
    .array(SOURCE_ENTRY, {
      error: issue =>
        Array.isArray(issue.input)
          ? undefined
          : `must be an array of tables - replace every [${table}.<name>] section with a [[${table}]] section and delete the name, because ${migration}`,
    })
    .optional();

const CONFIG_SCHEMA = z.object({
  system_prompt_file: z.string().optional(),
  vendors: VENDOR_TABLE.optional(),
  skills: ENTRY_LIST("skills", SKILL_TABLE_MIGRATION),
  subagents: ENTRY_LIST("subagents", SUBAGENT_TABLE_MIGRATION),
});

const PROJECT_CONFIG_SCHEMA = z.strictObject(
  {
    vendors: VENDOR_TABLE.optional(),
    skills: ENTRY_LIST("skills", SKILL_TABLE_MIGRATION),
  },
  {
    error: () =>
      `unknown key, ${PROJECT_CONFIG_FILE} supports only ${PROJECT_CONFIG_KEYS.join(", ")}`,
  },
);

const LOCK_SCHEMA = z.object({
  skills: z
    .record(
      z.string(),
      z.object({
        source: z.string(),
        subdir: z.string().optional(),
        commit: z.string(),
      }),
    )
    .optional(),
});

const problemPath = (path: readonly PropertyKey[]): string =>
  path.reduce<string>(
    (text, key) =>
      typeof key === "number"
        ? `${text}[${key}]`
        : text === ""
          ? String(key)
          : `${text}.${String(key)}`,
    "",
  );

const problems = (issue: z.core.$ZodIssue): string[] => {
  const label = (key?: string) => {
    const at = problemPath(
      key === undefined ? issue.path : [...issue.path, key],
    );
    return at === "" ? issue.message : `${at}: ${issue.message}`;
  };
  return issue.code === "unrecognized_keys"
    ? issue.keys.map(key => label(key))
    : [label()];
};

const parse = <T>(schema: z.ZodType<T>, value: unknown): T => {
  const result = schema.safeParse(value ?? {});
  if (result.success) {
    return result.data;
  }
  throw new ConfigError(result.error.issues.flatMap(problems));
};

const build = <T>(result: Result<T, string[]>): T => {
  if (result.ok) {
    return result.value;
  }
  throw new ConfigError(result.error);
};

export const decodeConfig = (value: unknown): Config =>
  build(buildConfig(parse(CONFIG_SCHEMA, value)));

export const decodeProjectConfig = (value: unknown): ProjectConfig =>
  build(buildProjectConfig(parse(PROJECT_CONFIG_SCHEMA, value)));

export const decodeLock = (value: unknown): ProjectLock => ({
  skills: parse(LOCK_SCHEMA, value).skills ?? {},
});

const tomlKey = (name: string): string =>
  BARE_KEY.test(name) ? name : JSON.stringify(name);

const tomlString = (text: string): string => JSON.stringify(text);

const sourceEntryLines = (entry: SourceEntry): string[] => {
  const lines = [`source = ${tomlString(entry.source)}`];
  if (entry.ref) {
    lines.push(`ref = ${tomlString(entry.ref)}`);
  }
  if (entry.subdir) {
    lines.push(`subdir = ${tomlString(entry.subdir)}`);
  }
  return lines;
};

export const encodeConfig = (config: Config): string => {
  const lines = [`system_prompt_file = ${tomlString(config.systemPromptFile)}`];
  for (const [name, vendor] of Object.entries(config.vendors)) {
    if (vendor === undefined) {
      continue;
    }
    lines.push("", `[vendors.${tomlKey(name)}]`, `enabled = ${vendor.enabled}`);
  }
  for (const table of ["skills", "subagents"] as const) {
    for (const entry of config[table]) {
      lines.push("", `[[${table}]]`, ...sourceEntryLines(entry));
    }
  }
  return `${lines.join("\n")}\n`;
};

const lockEntryTable = (name: string, entry: LockEntry): string => {
  const lines = [
    `[skills.${tomlKey(name)}]`,
    `source = ${tomlString(entry.source)}`,
  ];
  if (entry.subdir) {
    lines.push(`subdir = ${tomlString(entry.subdir)}`);
  }
  lines.push(`commit = ${tomlString(entry.commit)}`);
  return `${lines.join("\n")}\n`;
};

export const encodeLock = (lock: ProjectLock): string => {
  const tables = Object.entries(lock.skills).map(([name, entry]) =>
    lockEntryTable(name, entry),
  );
  return `${LOCK_HEADER}${tables.length === 0 ? "" : `\n${tables.join("\n")}`}`;
};
