import {
  type Config,
  DEFAULT_SYSTEM_PROMPT_FILE,
  type SourceEntry,
  type VendorConfig,
} from "../domain/config";
import {
  type LockEntry,
  PROJECT_CONFIG_FILE,
  type ProjectConfig,
  type ProjectLock,
} from "../domain/project";
import { SKILL_FILE } from "../domain/skill";
import { isVendor, VENDORS, type VendorName } from "../domain/vendor";

const BARE_KEY = /^[A-Za-z0-9_-]+$/;

const PROJECT_KEYS = ["skills"];

const LOCK_HEADER = "# generated by ponte - commit this file\n";

export class ConfigError extends Error {
  readonly problems: readonly string[];
  constructor(problems: readonly string[]) {
    super(problems.join("\n"));
    this.problems = problems;
  }
}

const readString = (value: unknown, path: string, problems: string[]): string | undefined => {
  if (value === undefined) return undefined;
  if (typeof value !== "string") {
    problems.push(`${path}: must be a string`);
    return undefined;
  }
  return value;
};

const readRequiredString = (
  value: unknown,
  path: string,
  problems: string[],
): string | undefined => {
  if (value === undefined) {
    problems.push(`${path}: is required`);
    return undefined;
  }
  return readString(value, path, problems);
};

const readBoolean = (value: unknown, path: string, problems: string[]): boolean | undefined => {
  if (value === undefined) return undefined;
  if (typeof value !== "boolean") {
    problems.push(`${path}: must be a boolean`);
    return undefined;
  }
  return value;
};

const readTable = (
  value: unknown,
  path: string,
  problems: string[],
): Record<string, unknown> | undefined => {
  if (value === undefined) return undefined;
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    problems.push(`${path}: must be a table`);
    return undefined;
  }
  return value as Record<string, unknown>;
};

const readEntries = <E>(
  value: unknown,
  path: string,
  problems: string[],
  readEntry: (raw: Record<string, unknown>, path: string, problems: string[]) => E | undefined,
): Record<string, E> => {
  const entries: Record<string, E> = {};
  const table = readTable(value, path, problems);
  if (!table) return entries;
  for (const [name, raw] of Object.entries(table)) {
    const rawEntry = readTable(raw, `${path}.${name}`, problems);
    if (!rawEntry) continue;
    const entry = readEntry(rawEntry, `${path}.${name}`, problems);
    if (entry !== undefined) entries[name] = entry;
  }
  return entries;
};

const readEntryList = <E>(
  value: unknown,
  path: string,
  problems: string[],
  readEntry: (raw: Record<string, unknown>, path: string, problems: string[]) => E | undefined,
): E[] => {
  const entries: E[] = [];
  if (value === undefined) return entries;
  if (!Array.isArray(value)) {
    problems.push(
      `${path}: must be an array of tables - replace every [${path}.<name>] section with a [[${path}]] section and delete the name, because ponte now reads the name from ${SKILL_FILE}`,
    );
    return entries;
  }
  for (const [index, raw] of value.entries()) {
    const rawEntry = readTable(raw, `${path}[${index}]`, problems);
    if (!rawEntry) continue;
    const entry = readEntry(rawEntry, `${path}[${index}]`, problems);
    if (entry !== undefined) entries.push(entry);
  }
  return entries;
};

const readVendorEntries = <E>(
  value: unknown,
  path: string,
  problems: string[],
  readEntry: (raw: Record<string, unknown>, path: string, problems: string[]) => E | undefined,
): Partial<Record<VendorName, E>> => {
  const entries: Partial<Record<VendorName, E>> = {};
  for (const [name, entry] of Object.entries(readEntries(value, path, problems, readEntry))) {
    if (!isVendor(name)) {
      problems.push(`${path}.${name}: unknown agent, expected one of ${VENDORS.join(", ")}`);
      continue;
    }
    entries[name] = entry;
  }
  return entries;
};

const readVendorConfig = (
  raw: Record<string, unknown>,
  path: string,
  problems: string[],
): VendorConfig => ({ enabled: readBoolean(raw.enabled, `${path}.enabled`, problems) ?? false });

const readSourceEntry = (
  raw: Record<string, unknown>,
  path: string,
  problems: string[],
): SourceEntry | undefined => {
  const source = readRequiredString(raw.source, `${path}.source`, problems);
  if (source === undefined) return undefined;
  const ref = readString(raw.ref, `${path}.ref`, problems);
  const subdir = readString(raw.subdir, `${path}.subdir`, problems);
  return { source, ...(ref !== undefined && { ref }), ...(subdir !== undefined && { subdir }) };
};

export const decodeConfig = (value: unknown): Config => {
  const problems: string[] = [];
  const root = readTable(value, "config", problems) ?? {};
  const config: Config = {
    systemPromptFile:
      readString(root.system_prompt_file, "system_prompt_file", problems) ??
      DEFAULT_SYSTEM_PROMPT_FILE,
    vendors: readVendorEntries(root.vendors, "vendors", problems, readVendorConfig),
    skills: readEntryList(root.skills, "skills", problems, readSourceEntry),
    subagents: readEntries(root.subagents, "subagents", problems, readSourceEntry),
  };
  if (problems.length > 0) throw new ConfigError(problems);
  return config;
};

const tomlKey = (name: string): string => (BARE_KEY.test(name) ? name : JSON.stringify(name));

const tomlString = (text: string): string => JSON.stringify(text);

const sourceEntryLines = (entry: SourceEntry): string[] => {
  const lines = [`source = ${tomlString(entry.source)}`];
  if (entry.ref) lines.push(`ref = ${tomlString(entry.ref)}`);
  if (entry.subdir) lines.push(`subdir = ${tomlString(entry.subdir)}`);
  return lines;
};

export const encodeConfig = (config: Config): string => {
  const lines = [`system_prompt_file = ${tomlString(config.systemPromptFile)}`];
  for (const [name, vendor] of Object.entries(config.vendors)) {
    if (vendor === undefined) continue;
    lines.push("", `[vendors.${tomlKey(name)}]`, `enabled = ${vendor.enabled}`);
  }
  for (const entry of config.skills) {
    lines.push("", "[[skills]]", ...sourceEntryLines(entry));
  }
  for (const [name, entry] of Object.entries(config.subagents)) {
    lines.push("", `[subagents.${tomlKey(name)}]`, ...sourceEntryLines(entry));
  }
  return `${lines.join("\n")}\n`;
};

export const decodeProjectConfig = (value: unknown): ProjectConfig => {
  const problems: string[] = [];
  const root = readTable(value, PROJECT_CONFIG_FILE, problems) ?? {};
  for (const key of Object.keys(root)) {
    if (PROJECT_KEYS.includes(key)) continue;
    problems.push(
      `${key}: unknown key, ${PROJECT_CONFIG_FILE} supports only ${PROJECT_KEYS.join(", ")}`,
    );
  }
  const config: ProjectConfig = {
    skills: readEntryList(root.skills, "skills", problems, readSourceEntry),
  };
  if (problems.length > 0) throw new ConfigError(problems);
  return config;
};

const readLockEntry = (
  raw: Record<string, unknown>,
  path: string,
  problems: string[],
): LockEntry | undefined => {
  const source = readRequiredString(raw.source, `${path}.source`, problems);
  const commit = readRequiredString(raw.commit, `${path}.commit`, problems);
  const subdir = readString(raw.subdir, `${path}.subdir`, problems);
  if (source === undefined || commit === undefined) return undefined;
  return { source, ...(subdir !== undefined && { subdir }), commit };
};

export const decodeLock = (value: unknown): ProjectLock => {
  const problems: string[] = [];
  const root = readTable(value, "lock", problems) ?? {};
  const lock: ProjectLock = { skills: readEntries(root.skills, "skills", problems, readLockEntry) };
  if (problems.length > 0) throw new ConfigError(problems);
  return lock;
};

const lockEntryLines = (name: string, entry: LockEntry): string => {
  const lines = [`[skills.${tomlKey(name)}]`, `source = ${tomlString(entry.source)}`];
  if (entry.subdir) lines.push(`subdir = ${tomlString(entry.subdir)}`);
  lines.push(`commit = ${tomlString(entry.commit)}`);
  return `${lines.join("\n")}\n`;
};

export const encodeLock = (lock: ProjectLock): string => {
  const tables = Object.entries(lock.skills).map(([name, entry]) => lockEntryLines(name, entry));
  return `${LOCK_HEADER}${tables.length === 0 ? "" : `\n${tables.join("\n")}`}`;
};
