set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Format the Bun/TS source under apps/ponte/src
typecheck:
    biome format --write ./apps/ponte/src

# Format everything
all: typecheck